import type { UserRole } from '@prisma/client';

export const AUDIT_CATEGORIES = {
  TECHNICAL: 'TECHNICAL',
  LOGIN: 'LOGIN',
  CRITICAL_READ: 'CRITICAL_READ',
  STANDARD: 'STANDARD',
  FINANCIAL_CRITICAL: 'FINANCIAL_CRITICAL'
} as const;

export type AuditCategory = (typeof AUDIT_CATEGORIES)[keyof typeof AUDIT_CATEGORIES];

export const AUDIT_ACTIONS = {
  CHANGE_REQUEST_CREATED: 'CHANGE_REQUEST_CREATED',
  CHANGE_REQUEST_CANCELLED: 'CHANGE_REQUEST_CANCELLED',
  CHANGE_REQUEST_APPROVED: 'CHANGE_REQUEST_APPROVED',
  CHANGE_REQUEST_REJECTED: 'CHANGE_REQUEST_REJECTED',
  CHANGE_APPLIED: 'CHANGE_APPLIED',
  VEHICLE_ARCHIVED: 'VEHICLE_ARCHIVED',
  ENTITY_UPDATED: 'ENTITY_UPDATED',
  MANAGER_INVITATION_CREATED: 'MANAGER_INVITATION_CREATED',
  MANAGER_INVITATION_REGENERATED: 'MANAGER_INVITATION_REGENERATED',
  MANAGER_ACTIVATED: 'MANAGER_ACTIVATED',
  MANAGER_DISABLED: 'MANAGER_DISABLED',
  MANAGER_ENABLED: 'MANAGER_ENABLED',
  REQUEST_STATUS_CHANGED: 'REQUEST_STATUS_CHANGED',
  REQUEST_MANAGER_ASSIGNED: 'REQUEST_MANAGER_ASSIGNED',
  REQUEST_MANAGER_REASSIGNED: 'REQUEST_MANAGER_REASSIGNED',
  REQUEST_MANAGER_UNASSIGNED: 'REQUEST_MANAGER_UNASSIGNED',
  REQUEST_COMPANY_CHANGED: 'REQUEST_COMPANY_CHANGED',
  REQUEST_ITEM_CREATED: 'REQUEST_ITEM_CREATED',
  REQUEST_ITEM_UPDATED: 'REQUEST_ITEM_UPDATED',
  REQUEST_ITEM_DELETED: 'REQUEST_ITEM_DELETED',
  REQUEST_ITEMS_SENT_FOR_APPROVAL: 'REQUEST_ITEMS_SENT_FOR_APPROVAL',
  REQUEST_ITEMS_CLIENT_APPROVAL_CHANGED: 'REQUEST_ITEMS_CLIENT_APPROVAL_CHANGED',
  COMMERCIAL_OFFER_CREATED: 'COMMERCIAL_OFFER_CREATED',
  COMMERCIAL_OFFER_UPDATED: 'COMMERCIAL_OFFER_UPDATED',
  COMMERCIAL_OFFER_ITEMS_CHANGED: 'COMMERCIAL_OFFER_ITEMS_CHANGED',
  COMMERCIAL_OFFER_SENT: 'COMMERCIAL_OFFER_SENT',
  COMMERCIAL_OFFER_APPROVED: 'COMMERCIAL_OFFER_APPROVED',
  COMMERCIAL_OFFER_REJECTED: 'COMMERCIAL_OFFER_REJECTED',
  COMMERCIAL_OFFER_CANCELLED: 'COMMERCIAL_OFFER_CANCELLED',
  COMMERCIAL_OFFER_DELETED: 'COMMERCIAL_OFFER_DELETED',
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_SENT: 'INVOICE_SENT',
  INVOICE_MARKED_PAID: 'INVOICE_MARKED_PAID',
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',
  INVOICE_PDF_OPENED: 'INVOICE_PDF_OPENED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',
  DOCUMENT_RENAMED: 'DOCUMENT_RENAMED',
  DOCUMENT_VISIBILITY_CHANGED: 'DOCUMENT_VISIBILITY_CHANGED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  COMPANY_UPDATED: 'COMPANY_UPDATED',
  COMPANY_BILLING_UPDATED: 'COMPANY_BILLING_UPDATED',
  COMPANY_PRIMARY_CONTACT_CHANGED: 'COMPANY_PRIMARY_CONTACT_CHANGED',
  COMPANY_MEMBER_ADDED: 'COMPANY_MEMBER_ADDED',
  COMPANY_MEMBER_REMOVED: 'COMPANY_MEMBER_REMOVED',
  CLIENT_BILLING_UPDATED: 'CLIENT_BILLING_UPDATED'
} as const;

export const AUDIT_SOURCES = {
  ADMIN_CRM: 'ADMIN_CRM',
  CLIENT_CABINET: 'CLIENT_CABINET',
  SYSTEM: 'SYSTEM'
} as const;

export type AuditSource = (typeof AUDIT_SOURCES)[keyof typeof AUDIT_SOURCES];

export type AuditRequestContext = {
  ipAddress?: string | null;
  userAgent?: string | null;
};

export const AUDIT_ENTITY_TYPES = {
  REQUEST: 'REQUEST',
  REQUEST_ITEM: 'REQUEST_ITEM',
  VEHICLE: 'VEHICLE',
  REQUEST_DOCUMENT: 'REQUEST_DOCUMENT',
  DOCUMENT: 'DOCUMENT',
  COMMERCIAL_OFFER: 'COMMERCIAL_OFFER',
  INVOICE: 'INVOICE',
  COMPANY: 'COMPANY',
  CHANGE_REQUEST: 'CHANGE_REQUEST',
  USER: 'USER',
  TEAM_MEMBER: 'TEAM_MEMBER',
  CLIENT: 'CLIENT',
  EQUIPMENT_TYPE: 'EQUIPMENT_TYPE',
  MANUFACTURER: 'MANUFACTURER',
  AUTH_SESSION: 'AUTH_SESSION',
  TELEGRAM_REQUEST: 'TELEGRAM_REQUEST',
  SYSTEM: 'SYSTEM'
} as const;

export type AuditActor =
  | { type: 'USER'; id: string }
  | { type: 'SYSTEM'; name: string }
  | { type: 'ANONYMOUS' };

export function auditUserActor(id: string): AuditActor {
  return { type: 'USER', id };
}

export function auditSystemActor(name: string): AuditActor {
  return { type: 'SYSTEM', name };
}

export function auditAnonymousActor(): AuditActor {
  return { type: 'ANONYMOUS' };
}

export type AuditActorSnapshot = {
  actorId: string | null;
  actorName: string | null;
  actorEmail: string | null;
  actorRole: UserRole | null;
};

export function canReadFullAuditLog(role: UserRole | string | null | undefined) {
  return role === 'ADMIN';
}
