ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'AUTH_ATTEMPT';
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'INVITATION';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTH_LOGIN_SUCCEEDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTH_LOGIN_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTH_LOGIN_BLOCKED_DISABLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTH_LOGIN_BLOCKED_PENDING';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTH_LOGOUT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTH_INVITATION_ACCEPTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTH_SESSION_INVALIDATED';
