export const EQUIPMENT_TAXONOMY_ADMIN_ENABLED = false;
export const EQUIPMENT_TAXONOMY_REQUEST_FIELDS_ENABLED = false;
export const EQUIPMENT_TAXONOMY_TELEGRAM_FIELDS_ENABLED = false;
export const EQUIPMENT_TAXONOMY_VEHICLE_FIELDS_ENABLED = false;
export const EQUIPMENT_TAXONOMY_REQUEST_ITEM_FIELDS_ENABLED = false;
export const EQUIPMENT_TEXT_FIELD_MAX_LENGTH = 120;
